#!/usr/bin/env node
/**
 * Scans /apps/* for meta.json files and rewrites the PROJECTS array
 * at the bottom of projects.js. Run locally or via CI before deploy.
 *
 * meta.json fields:
 *   name       string   — display name
 *   category   string   — chip label (e.g. "Tool", "Game")
 *   blurb      string   — one-sentence description
 *   hue        number   — oklch hue (0–360) for tile colour
 *   pattern    string   — thumbnail style: dots | stripes | arch | grid | waves | blocks
 *   date       string   — ISO date added (YYYY-MM-DD)
 */
const fs   = require('fs');
const path = require('path');

const appsDir      = path.join(__dirname, 'apps');
const projectsFile = path.join(__dirname, 'projects.js');

const projects = [];

if (fs.existsSync(appsDir)) {
  fs.readdirSync(appsDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name))
    .forEach(d => {
      const metaPath = path.join(appsDir, d.name, 'meta.json');
      if (!fs.existsSync(metaPath)) return;
      const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
      projects.push({
        slug:     d.name,
        path:     `apps/${d.name}/`,
        uses:     0,
        hue:      180,
        pattern:  'blocks',
        ...meta,
      });
    });
}

// Preserve everything above the generated marker, then rewrite the array.
const current  = fs.readFileSync(projectsFile, 'utf8');
const marker   = '// ── generated by generate.js — do not edit below this line ──';
const hubPart  = current.includes(marker)
  ? current.slice(0, current.indexOf(marker))
  : current + '\n';

const output = `${hubPart}${marker}\nwindow.PROJECTS = ${JSON.stringify(projects, null, 2)};\n`;
fs.writeFileSync(projectsFile, output);
console.log(`projects.js updated — ${projects.length} app(s)`);
